arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005      
  kinematics_solver_timeout: 0.005
  position_only_ik: true


# This file configures the Inverse Kinematics (IK) solver for the robot’s arm group.

# Purpose:
    # Defines how MoveIt computes joint angles to achieve desired end-effector poses.
    # Sets solver parameters like timeout and search resolution for IK calculations.

# Key Settings:
    # kinematics_solver: Specifies the IK plugin to use (KDL in this case).
    # kinematics_solver_timeout: Maximum time allowed for IK computations (5 ms here).
    # kinematics_solver_search_resolution: How finely the solver samples joint space.
    # position_only_ik: true → computes only end-effector position, ignoring orientation (since your 3-DOF arm can’t control orientation independently).