moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_4
      - joint_5


# This file connects MoveIt to ros2_control so that planned trajectories are actually sent to your robot’s joint controllers.

# Purpose:
    # Specifies which controllers MoveIt should use for different parts of the robot (arm, gripper).
    # Maps MoveIt’s trajectory commands to ros2_control action servers.

# Each controller block tells MoveIt:
    # Which action interface to use (follow_joint_trajectory)
    # What joint names the controller manages