cartesian_limits:
  max_trans_vel: 1.0  # m/s
  max_trans_acc: 2.25  # m/s^2
  max_trans_dec: -5.0  # m/s^2
  max_rot_vel: 1.57  # rad/s


# This file defines Cartesian motion limits (tool-space speeds/accelerations) when MoveIt performs Cartesian path planning.